pro3d_path : 'C:\Users\migue\Documents\TU Graz\Asignaturas\Master Thesis\Pro3D\PRo3D 2.10.4 - Prerelease\PRo3D.Viewer.exe'
scenes:
  - 'StereoMosaic'
shatter_cones:
  - 'Terny_Crater_Ukraine_Model_1'
  - 'Steinheim_Germany_Model_1'
  - 'Vista_Alegra_Brazil_RC1_Model_1'
  - 'Wells_creek_Tennessee_Model_1'
shatter_cone_settings:
  min: 0
  max: 3
camera_centers:
  - [-2486880.90, 2288937.08, -279361.15]
rotation: 1

    