obj2heightmap:
  path_in: 'E:\TFM\Bakeoff 2020\Job_0796_003477_MSLMST_obj_cart_single\'
  path_out: "D:/Master Thesis/try/"
  obj_in: "T000_P007_C000.obj"
  heightmap_out: "gale_crater.png"
  path_to_converter:
  r16_out: "marstest.r16"
fitgroundplane:
  malloc_discard_instances: 0.95
  malloc_step: 0.01
blenderprocessor:
  path_in: 'E:\TFM\Bakeoff 2020\CART'
  path_out: "E:/TFM/Blender Processor Results/"
psganpreprocess:
  path_in: "E:\\TFM\\Blender Processor Results\\2020-11-23 21h49m36s"
  path_out: "\\preprocessed"
  processPool: 32
  chunk_res: [256,256]
  max_empty: 0.001
obj_converter:
  path_in: 'C:\Users\migue\Desktop'
  psgan_output_size: 128
  padding_psgan: 2
  is_image: false