obj2heightmap:
  path_in: 'E:\TFM\Bakeoff 2020\Job_0796_003477_MSLMST_obj_cart_single\'
  path_out: "D:/Master Thesis/try/"
  obj_in: "T000_P007_C000.obj"
  heightmap_out: "gale_crater.png"
  path_to_converter:
  r16_out: "marstest.r16"
fitgroundplane:
  malloc_discard_instances: 0.95
  malloc_step: 0.01
blenderprocessor:
  path_in: "F:\\Storage\\Master Thesis - Storage\\Training data - selected OBJs\\"
  path_out: "F:\\Storage\\Master Thesis - Storage\\Blender Processor Results\\Training data - selected OBJs - Sun try"
blendersnapshots:
  path_out: "F:\\Storage\\Master Thesis - Storage\\Blender Snapshot Results\\First attempt"
  no_snaps: 1000
  coordinates:
    upper_x: 8.0385
    lower_x: -7.9255
    upper_y: -84.557
    lower_y: -82.063
    upper_z: 7.9429
    lower_z: -8.0700
sganpreprocess:
  path_in: 'F:\Storage\Master Thesis - Storage\Blender Processor Results\Training data - selected OBJs - Sun try - 40_2021-06-25 00h00m23s'
  path_out: 'preprocessed_global_average'
  max_empty: 0
  min_colour_value: 50
  random_crop_size: 512
  no_crops: 32
obj_converter:
  path_in: 'F:\Storage\Master Thesis - Storage\SGAN Results\Complete\crops_rescaled\wgan'
  vmax: 1.1582716703414917
  vmin: 1
  psgan_output_size: 512
  padding_psgan: 2
  is_image: false
sigma_calculator:
  path_in: 'F:\Storage\Master Thesis - Storage\Blender Processor Results\debug_light2021-05-09 21h08m00s'
  path_out: 'F:\Storage\Master Thesis - Storage\Blender Processor Results\debug_light2021-05-09 21h08m00s'
random_crops:
  file_in: 'F:\Storage\Master Thesis - Storage\Blender Processor Results\Training data - selected OBJs2021-05-10 20h08m44s\T000_P060_C000.npy'
  path_out: 'F:\Storage\Master Thesis - Storage\Blender Processor Results\final_random_crop'
  initial_crop_size: 0
  random_crop_size: 512
  no_crops: 64
  max_empty: 0