obj2heightmap:
  path_in: 'E:\TFM\Bakeoff 2020\Job_0796_003477_MSLMST_obj_cart_single\'
  path_out: "D:/Master Thesis/try/"
  obj_in: "T000_P007_C000.obj"
  heightmap_out: "gale_crater.png"
  path_to_converter:
  r16_out: "marstest.r16"
fitgroundplane:
  malloc_discard_instances: 0.95
  malloc_step: 0.01
blenderprocessor:
  path_in: "E:\\Master Thesis - Storage\\Training data - selected OBJs\\"
  path_out: "E:\\Master Thesis - Storage\\Blender Processor Results\\Training data - selected OBJs"
sganpreprocess:
  path_in: 'E:\Master Thesis - Storage\Blender Processor Results\Training data - selected OBJs2021-05-10 20h08m44s'
  path_out: "\\depthColourFixed"
  chunk_res: [512,512]
  max_empty: 5.0
obj_converter:
  path_in: 'E:\Master Thesis - Storage\SGAN Results\Complete\EnvGen_colourFixed\Selected'
  psgan_output_size: 256
  padding_psgan: 2
  is_image: false
sigma_calculator:
  path_in: 'E:\Master Thesis - Storage\Blender Processor Results\debug_light2021-05-09 21h08m00s'
  path_out: 'E:\Master Thesis - Storage\Blender Processor Results\debug_light2021-05-09 21h08m00s'