obj2heightmap:
  path_in: 'E:\TFM\Bakeoff 2020\Job_0796_003477_MSLMST_obj_cart_single\'
  path_out: "D:/Master Thesis/try/"
  obj_in: "T000_P007_C000.obj"
  heightmap_out: "gale_crater.png"
  path_to_converter:
  r16_out: "marstest.r16"
fitgroundplane:
  malloc_discard_instances: 0.95
  malloc_step: 0.01
blenderprocessor:
  path_in: 'E:\TFM\Blender Processor Results\2020-11-09 14h48m18s\psgan_out'
  path_out: "E:/TFM/Blender Processor Results/try"
psganpreprocess:
  path_in: "E:/TFM/Blender Processor Results/2020-11-09 14h48m18s"
  processPool: 16
  chunk_res: [256,256]
  max_empty: 5
obj_converter:
  path_in: 'E:\TFM\Blender Processor Results\2020-11-09 14h48m18s\psgan_out'
  psgan_output_size: 160
  padding_psgan: 2