obj2heightmap:
  path_in: 'E:\TFM\Bakeoff 2020\Job_0796_003477_MSLMST_obj_cart_single\'
  path_out: "D:/Master Thesis/try/"
  obj_in: "T000_P007_C000.obj"
  heightmap_out: "gale_crater.png"
  path_to_converter:
  r16_out: "marstest.r16"
fitgroundplane:
  malloc_discard_instances: 0.95
  malloc_step: 0.01
blenderprocessor:
  path_in: "E:\\Master Thesis - Storage\\Training data - selected OBJs\\"
  path_out: "E:\\Master Thesis - Storage\\Blender Processor Results\\Training data - selected OBJs"
sganpreprocess:
  path_in: 'E:\Master Thesis - Storage\Blender Processor Results\Training data - selected OBJs2021-05-10 20h08m44s'
  path_out: '\final_dataset'
  max_empty: 0
  random_crop_size: 128
  no_crops: 16
obj_converter:
  path_in: 'E:\Master Thesis - Storage\SGAN Results\Complete\EnvGen_colourFixed\crops_rescaled\wgan'
  vmax: -0.9835078
  vmin: -0.98443973
  psgan_output_size: 512
  padding_psgan: 2
  is_image: false
sigma_calculator:
  path_in: 'E:\Master Thesis - Storage\Blender Processor Results\debug_light2021-05-09 21h08m00s'
  path_out: 'E:\Master Thesis - Storage\Blender Processor Results\debug_light2021-05-09 21h08m00s'
random_crops:
  file_in: 'E:\Master Thesis - Storage\Blender Processor Results\randomcrops\T000_P060_C000_4.npy'
  path_out: 'E:\Master Thesis - Storage\Blender Processor Results\randomcrops\rescaled'
  initial_crop_size: 480
  random_crop_size: 160
  no_crops: 32